# src/Acme/UserBundle/Resources/config/services.yml
services:
    forum_user.registration.form.type:
        class: Forum\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: forum_user_registration }
