Forum\ScaredForumBundle\Entity\Forum:
    type: entity
    table: null
    repositoryClass: Forum\ScaredForumBundle\Entity\ForumRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
        threads_count:
            type: integer
            default: 0
        posts_count:
            type: integer
            default: 0


        created_at:
          type: date
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          gedmo:
            timestampable:
              on: update
    manyToOne:
        group:
            targetEntity: ForumGroups
        created_by:
            targetEntity: User

    lifecycleCallbacks: {  }
