Forum\ScaredForumBundle\Entity\ForumGroups:
    type: entity
    table: null
    repositoryClass: Forum\ScaredForumBundle\Entity\ForumGroupsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
        created_at:
          type: date
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          gedmo:
            timestampable:
              on: update
    manyToOne:
        created_by:
            targetEntity: User
    lifecycleCallbacks: {  }
