<?php

namespace Forum\ScaredForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function getThreadsByForum($fid){
        $query = $this->getEntityManager()
            ->createQuery('SELECT t FROM ScaredForumBundle:Thread t
                    JOIN t.forum f WHERE f.id = :fid ORDER BY t.id');

        $query->setParameter('fid', $fid);

        return $query->getResult();
    }
}
