<?php

namespace Forum\ScaredForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumGroupsRepository extends EntityRepository
{
}
