<?php

namespace Forum\ScaredForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumGroupsRepository extends EntityRepository
{
    public function getForumsByGroup($gid){
        $query = $this->getEntityManager()
            ->createQuery('SELECT f FROM ScaredForumBundle:Forum f
                    JOIN f.group g WHERE g.id = :gid ORDER BY f.id DESC');

        $query->setParameter('gid', $gid);

        return $query->getResult();
    }

    public function getLatest3Forums(){

    }
}
