<?php

namespace Forum\ScaredForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
    public function getPostsByThread($tid){
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM ScaredForumBundle:Post p
                    JOIN p.thread t WHERE t.id = :tid ORDER BY p.id');

        $query->setParameter('tid', $tid);

        return $query->getResult();
    }
}
